### ISSUE TITLE
Incomplete Project Files

### ISSUE THREAD

**Issue by theyashl** [Tejas-Gosavi/Farmer-management-system-project#1]
You'll have to upload complete project files. As you only uploaded application files. But to run a project complete project file is needed. Since you can't run the server without **_manage.py_** file, and this file belongs to the project-name directory.

**Comment by Tejas-Gosavi** [comment]
@theyashl 
Hello yash, i am using flask framework in backend and in flask we use app.py or application.py file to run server.

**Comment by tejas-gosavi** [comment]
@theyashl
Hello yash, i am using flask framework in backend and in flask we use app.py or application.py file to run server.

**Comment by theyashl** [comment]
Ohh sorry! I got confused with framework!
